# Package Build Configuration 
name: PCK.AUTOMIC_TMPL_ORACLEDB

source: ae
  
# binary object resource mapping will be defined here
binaries:
  
  - object: RESOURCES/LIBS/PCK.AUTOMIC_ARA.PRV.STORE
    resources: 
      - name: DMTOOLS.JAR
        type: BINARY
        path: tools/aratools/target/DMTOOLS.JAR
        version: 1.0.0